select ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 2), 'km') as TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') as AVERAGE_DISTANCE
from SUBWAY_DISTANCE 
group by ROUTE
order by SUM(D_CUMULATIVE) desc