select YEAR(a.DIFFERENTIATION_DATE) as YEAR,  ((
    select MAX(b.SIZE_OF_COLONY)
    from ECOLI_DATA b
    where YEAR(a.DIFFERENTIATION_DATE) = YEAR(b.DIFFERENTIATION_DATE)
) - a.SIZE_OF_COLONY) as YEAR_DEV, a.ID as ID
from ECOLI_DATA a
order by YEAR, YEAR_DEV